# FROM node:18
# WORKDIR /frontend
# COPY package*.json ./
# RUN npm install
# COPY . ./
# CMD ["npm", "run", "dev"]

# Use the official Node.js v14 image as base
FROM node:18

# Set the working directory to /app
WORKDIR /frontend

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . ./

# Set the environment variable to development
ENV NODE_ENV=development

# Set the default command to start the development server
CMD ["npm", "run", "dev"]
